name: PlanetFxTempleRun
version: 2.0.2
author: Sebastian Mikolai

main: de.SebastianMikolai.PlanetFx.TempleRun.TempleRun

commands:
  pfxtr:
    description: PlanetFxTempleRun Commands
    usage: /pfxtr